version: 0.0
os: linux

hooks:
  - location: scripts/git_pull.sh
    timeout: 300
    runas: chatapp

  - location: scripts/activate_venv_and_install_requirements.sh
    timeout: 300
    runas: chatapp

  - location: scripts/migrate_and_restart_django.sh
    timeout: 300
    runas: chatapp
