version: 0.0
os: linux

files:
  - source: / 
    destination: /new_chatapp

hooks:
  BeforeInstall:
    - location: scripts/activate_venv_and_install_requirements.sh
      timeout: 300
      runas: root


  ApplicationStart:
    - location: scripts/migrate_and_restart_django.sh
      timeout: 300
      runas: root
