version: 0.0
os: linux


hooks:
  BeforeInstall:
    - location: scripts/activate_venv_and_install_requirements.sh
      timeout: 300
      runas: chatapp

  ApplicationStart:
    - location: scripts/migrate_and_restart_django.sh
      timeout: 300
      runas: chatapp
