version: 0.0
os: linux

hooks:
  BeforeInstall:
    - location: scripts/git_pull.sh
      runas: chatapp

    - location: scripts/activate_venv_and_install_requirements.sh
      runas: chatapp

  ApplicationStart:
    - location: scripts/migrate_and_restart_django.sh
      runas: chatapp
