version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install virtualenv
      - virtualenv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR